### ISSUE TITLE
Netflix on chromium60

### ISSUE THREAD

**Issue by Goruti** [kusti8/chromium-build#2]
Hi @kusti8 ,

First of all thanks for build chromium for Netflix (and many other services which required widevine).

I recently upgraded my RPI to "Stretch" that bring my chromium-browser to version 60.0. Is it possible for you to generate a new deb package base on this version?

Unfortunaly the version posted for [netflix-1.0.0](https://github.com/kusti8/chromium-build/releases/tag/netflix-1.0.0) is 56.

I am clearly not a king in all of this programming things :(

I would appreciate a lot!

Thanks!
Diego

**Comment by kusti8** [comment]
I'm working on it now.

**Comment by olejon** [comment]
Hoping for a release soon! Great work :) Your release lagged badly on my Pi 2. Tried just one website, but it offers to go all the way down to 360p and still lagged badly.

You seem to be an expert on this, so why does it not work anymore to download ChromeOS recovery for the same architecture as Pi and moving the widevine components to the Chromium that comes with Raspbian? It did before as I have read.

**Comment by kusti8** [comment]
I don't know why widevine doesn't work with the new version. I've tried to get it to work, with new and old versions of the library, recompiling chromium as well, but it still doesn't work. I don't know why, and I don't have enough time to keep on trying.

**Comment by olejon** [comment]
Alright, I get that. These things take a lot of time, compiling, trying and failing. I hope maybe Firefox can ship a version in the future? After all they do it on x86, and downloads Widevine automatically. Widevine works on ARM since it works on Chromebooks. Someone must be holding Mozilla back, but I don't understand what they fear if they allow Firefox to do the same on ARM as x86... HTML5 DRM doesn't exactly stop people from recording video. It just makes it more difficult. But a browser on x86 is enough...

People seem to report your build as the only solution for now, and it seems to work with Netflix although I haven't tried. Maybe because the site I tried was too heavy or not trying on a Pi 3, which I have now. Anyway, can't stick with an old Chromium version - not good security practive.

Thanks for trying with newer versions! Cheers :)

**Comment by vdpollm** [comment]
Hi. will this work on a Rock64?
